language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
env:
  -
  - MONGOHQ_URL='mongodb://dummy'
  - MONGOLAB_URI='mongodb://dummy'
  - MONGOHQ_URL='mongodb://dummy1' MONGOLAB_URI='mongodb://dummy2'
install:
  - pip install nose
  - pip install .
script: make test
